#include "draw.h"
#include "patch.h"
#include "mod.h"
#include "evt_cmd.h"
#include "gc/OSArena.h"
#include "gc/os.h"
#include "ttyd/dispdrv.h"
#include "ttyd/evtmgr.h"
#include "ttyd/fontmgr.h"
#include "ttyd/mariost.h"
#include "ttyd/item_data.h"
#include "ttyd/battle_event_cmd.h"
#include "ttyd/battle_event_default.h"
#include "ttyd/sac_bakugame.h"
#include "ttyd/battle.h"
#include "ttyd/battle_damage.h"
#include "ttyd/battle_mario.h"
#include "ttyd/battle_camera.h"
#include "ttyd/battle_unit.h"
#include "ttyd/battle_database_common.h"
#include "ttyd/evt_snd.h"
#include "ttyd/evt_sub.h"
#include "ttyd/evt_eff.h"
#include "ttyd/evt_audience.h"
#include "ttyd/unit_party_vivian.h"

using namespace ttyd;
using namespace battle_event_cmd;
using namespace battle_event_default;
using namespace battle_mario;
using namespace battle_camera;
using namespace evt_snd;
using namespace evt_sub;
using namespace evt_audience;
using namespace unit_party_vivian;

namespace mod {

EVT_BEGIN(hammer_move)
    USER_FUNC(btlevtcmd_check_battleflag, LW(0), 2)
    IF_NOT_EQUAL(LW(0), 0)
        SET(LW(12), PTR(&marioDefaultWeapon_Hammer))
        USER_FUNC(btlevtcmd_GetFirstAttackTarget, LW(3), LW(4))
        IF_EQUAL(LW(3), -1)
            GOTO(99)
        END_IF()
        USER_FUNC(evt_btl_camera_set_mode, 0, 7)
        USER_FUNC(evt_btl_camera_set_homing_unit, 0, LW(3), -1)
        USER_FUNC(evt_btl_camera_set_zoom, 0, 300)
        USER_FUNC(evt_btl_camera_set_moveSpeedLv, 0, 2)
        USER_FUNC(btlevtcmd_GetHomePos, -2, LW(0), LW(1), LW(2))
        USER_FUNC(btlevtcmd_FaceDirectionSub, -2, LW(0), 250)
        USER_FUNC(btlevtcmd_SetPos, -2, LW(0), LW(1), LW(2))
        WAIT_FRM(30)
    ELSE()
        USER_FUNC(btlevtcmd_CommandGetWeaponAddress, -2, LW(12))
        USER_FUNC(btlevtcmd_GetSelectEnemy, LW(3), LW(4))
        IF_EQUAL(LW(3), -1)
            GOTO(99)
        END_IF()
        USER_FUNC(btlevtcmd_AttackDeclare, -2, LW(3), LW(4))
        USER_FUNC(btlevtcmd_WaitGuardMove)
        USER_FUNC(btlevtcmd_PayWeaponCost, -2, LW(12))
        USER_FUNC(btlevtcmd_RunDataEventChild, -2, 7)
        RUN_CHILD_EVT(PTR(&marioAttackEvent_MajinaiPowerUpCheck))
        USER_FUNC(evt_btl_camera_set_mode, 0, 11)
        USER_FUNC(evt_btl_camera_set_homing_unitparts, 0, -2, 1, LW(3), LW(4))
        USER_FUNC(evt_btl_camera_set_moveSpeedLv, 0, 1)
        USER_FUNC(evt_btl_camera_set_zoom, 0, 300)
    END_IF()
    USER_FUNC(btlevtcmd_check_battleflag, LW(0), 2)
    IF_EQUAL(LW(0), 0)
        USER_FUNC(btlevtcmd_GetWeaponActionLv, LW(12), LW(0))
        USER_FUNC(btlevtcmd_AcSetDifficulty, -2, LW(0))
        SWITCH(LW(12))
            CASE_EQUAL(PTR(&marioDefaultWeapon_Hammer))
                USER_FUNC(btlevtcmd_AcSetParamAll, 4, 25, 0, 0, 0, PTR(0xf1194d80), PTR(0xf1194d80), PTR(0xf1194d80))
            CASE_EQUAL(PTR(&badgeWeapon_ConfuseHammer))
                USER_FUNC(btlevtcmd_AcSetParamAll, 4, 30, 0, 0, 0, PTR(0xf1194d80), PTR(0xf1194d80), PTR(0xf1194d80))
            CASE_EQUAL(PTR(&badgeWeapon_TsuranukiNaguri))
                USER_FUNC(btlevtcmd_AcSetParamAll, 4, 30, 0, 0, 0, PTR(0xf1194d80), PTR(0xf1194d80), PTR(0xf1194d80))
            CASE_ETC()
                USER_FUNC(btlevtcmd_AcSetParamAll, 4, 40, 0, 0, 0, PTR(0xf1194d80), PTR(0xf1194d80), PTR(0xf1194d80))
        END_SWITCH()
        USER_FUNC(btlevtcmd_AcSetFlag, 0)
        USER_FUNC(btlevtcmd_SetupAC, -2, 3, 1, 0)
    END_IF()
    USER_FUNC(btlevtcmd_check_battleflag, LW(0), 2)
    IF_NOT_EQUAL(LW(0), 0)
        USER_FUNC(btlevtcmd_GetHomePos, -2, LW(0), LW(1), LW(2))
        USER_FUNC(btlevtcmd_FaceDirectionSub, -2, LW(0), 250)
        USER_FUNC(btlevtcmd_SetPos, -2, LW(0), LW(1), LW(2))
        WAIT_MSEC(1000)
        USER_FUNC(btlevtcmd_SetMoveSpeed, -2, FLOAT(5.0))
        USER_FUNC(btlevtcmd_AnimeChangePoseType, -2, 1, 42)
        USER_FUNC(btlevtcmd_GetHitPos, LW(3), LW(4), LW(0), LW(1), LW(2))
        USER_FUNC(btlevtcmd_GetPos, -2, PTR(0xf1194d80), LW(1), PTR(0xf1194d80))
        USER_FUNC(btlevtcmd_FaceDirectionAdd, LW(3), LW(0), 35)
        USER_FUNC(btlevtcmd_SetMoveSpeed, -2, FLOAT(5.0))
        ADD(LW(2), 5)
        USER_FUNC(btlevtcmd_CalculateFaceDirection, -2, -1, LW(0), LW(2), 1, LW(15))
        USER_FUNC(btlevtcmd_ChangeFaceDirection, -2, LW(15))
        USER_FUNC(btlevtcmd_GetMoveFrame, -2, LW(0), LW(1), LW(2), 0, LW(7))
        IF_LARGE(LW(7), 22)
            SUB(LW(7), 22)
        ELSE()
            SUB(LW(7), 22)
            MUL(LW(7), -1)
        END_IF()
        BROTHER_EVT()
            WAIT_FRM(LW(7))
            USER_FUNC(btlevtcmd_GetWeaponActionLv, LW(12), LW(0))
            USER_FUNC(btlevtcmd_AcSetDifficulty, -2, LW(0))
            SWITCH(LW(12))
                CASE_EQUAL(PTR(&marioDefaultWeapon_Hammer))
                    USER_FUNC(btlevtcmd_AcSetParamAll, 4, 25, 0, 0, 0, PTR(0xf1194d80), PTR(0xf1194d80), PTR(0xf1194d80))
                CASE_EQUAL(PTR(&badgeWeapon_ConfuseHammer))
                    USER_FUNC(btlevtcmd_AcSetParamAll, 4, 30, 0, 0, 0, PTR(0xf1194d80), PTR(0xf1194d80), PTR(0xf1194d80))
                CASE_EQUAL(PTR(&badgeWeapon_TsuranukiNaguri))
                    USER_FUNC(btlevtcmd_AcSetParamAll, 4, 30, 0, 0, 0, PTR(0xf1194d80), PTR(0xf1194d80), PTR(0xf1194d80))
                CASE_ETC()
                    USER_FUNC(btlevtcmd_AcSetParamAll, 4, 40, 0, 0, 0, PTR(0xf1194d80), PTR(0xf1194d80), PTR(0xf1194d80))
            END_SWITCH()
            USER_FUNC(btlevtcmd_AcSetFlag, 0)
            USER_FUNC(btlevtcmd_SetupAC, -2, 3, 1, 0)
        END_BROTHER()
        USER_FUNC(btlevtcmd_MovePosition, -2, LW(0), LW(1), LW(2), 0, -1, 0)
    ELSE()
        USER_FUNC(btlevtcmd_AnimeChangePoseType, -2, 1, 42)
        USER_FUNC(btlevtcmd_GetHitPos, LW(3), LW(4), LW(0), LW(1), LW(2))
        USER_FUNC(btlevtcmd_GetPos, -2, PTR(0xf1194d80), LW(1), PTR(0xf1194d80))
        USER_FUNC(btlevtcmd_FaceDirectionAdd, LW(3), LW(0), 35)
        USER_FUNC(btlevtcmd_SetMoveSpeed, -2, FLOAT(3.0))
        ADD(LW(2), 5)
        USER_FUNC(btlevtcmd_CalculateFaceDirection, -2, -1, LW(0), LW(2), 1, LW(15))
        USER_FUNC(btlevtcmd_ChangeFaceDirection, -2, LW(15))
        USER_FUNC(btlevtcmd_MovePosition, -2, LW(0), LW(1), LW(2), 0, -1, 0)
    END_IF()
    USER_FUNC(btlevtcmd_CalculateFaceDirection, -2, -1, LW(3), LW(4), 16, LW(15))
    USER_FUNC(btlevtcmd_ChangeFaceDirection, -2, LW(15))
    USER_FUNC(btlevtcmd_PreCheckDamage, -2, LW(3), LW(4), LW(12), 256, LW(6))
    IF_EQUAL(LW(6), 5)
        USER_FUNC(btlevtcmd_StopAC)
        USER_FUNC(btlevtcmd_CheckDamage, -2, LW(3), LW(4), LW(12), 256, LW(5))
        RETURN()
    END_IF()
    IF_EQUAL(LW(12), PTR(&badgeWeapon_TsuranukiNaguri))
        USER_FUNC(_get_mario_hammer_lv, LW(0))
        SWITCH(LW(0))
            CASE_EQUAL(2)
                SET(LW(0), PTR("M_H_5A"))
                SET(LW(1), PTR("M_H_5B"))
                SET(LW(2), PTR("M_H_14"))
            CASE_EQUAL(3)
                SET(LW(0), PTR("M_H_9A"))
                SET(LW(1), PTR("M_H_9B"))
                SET(LW(2), PTR("M_H_15"))
            CASE_ETC()
                SET(LW(0), PTR("M_H_1A"))
                SET(LW(1), PTR("M_H_1B"))
                SET(LW(2), PTR("M_H_13"))
        END_SWITCH()
    ELSE()
        USER_FUNC(_get_mario_hammer_lv, LW(0))
        SWITCH(LW(0))
            CASE_EQUAL(2)
                SET(LW(0), PTR("M_H_5A"))
                SET(LW(1), PTR("M_H_5B"))
                SET(LW(2), PTR("M_H_5C"))
            CASE_EQUAL(3)
                SET(LW(0), PTR("M_H_9A"))
                SET(LW(1), PTR("M_H_9B"))
                SET(LW(2), PTR("M_H_9C"))
            CASE_ETC()
                SET(LW(0), PTR("M_H_1A"))
                SET(LW(1), PTR("M_H_1B"))
                SET(LW(2), PTR("M_H_1C"))
        END_SWITCH()
    END_IF()
    //USER_FUNC(btlevtcmd_SetupAC, -2, 3, 1, 0)
    USER_FUNC(evt_btl_camera_set_moveSpeedLv, 0, 1)
    USER_FUNC(evt_btl_camera_set_zoom, 0, 350)
    USER_FUNC(btlevtcmd_snd_se, -2, PTR("SFX_VOICE_MARIO_POWER2"), PTR(0xf1194d80), 0, PTR(0xf1194d80))
    USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, LW(0))
    USER_FUNC(_get_mario_hammer_lv, LW(0))
    SWITCH(LW(0))
        CASE_EQUAL(2)
            USER_FUNC(btlevtcmd_snd_se, -2, PTR("SFX_MARIO_HAMMER_HOLD2"), PTR(0xf1194d80), 0, PTR(0xf1194d80))
        CASE_EQUAL(1)
            USER_FUNC(btlevtcmd_snd_se, -2, PTR("SFX_MARIO_HAMMER_HOLD1"), PTR(0xf1194d80), 0, PTR(0xf1194d80))
        CASE_ETC()
            USER_FUNC(btlevtcmd_snd_se, -2, PTR("SFX_MARIO_HAMMER_HOLD3"), PTR(0xf1194d80), 0, PTR(0xf1194d80))
    END_SWITCH()
    BROTHER_EVT()
        SWITCH(LW(12))
            CASE_EQUAL(PTR(&badgeWeapon_ConfuseHammer))
                SET(LW(13), 0)
            CASE_EQUAL(PTR(&badgeWeapon_TsuranukiNaguri))
                SET(LW(13), 2)
        END_SWITCH()
        SWITCH(LW(12))
            CASE_OR(PTR(&badgeWeapon_ConfuseHammer))
            CASE_OR(PTR(&badgeWeapon_TsuranukiNaguri))
                USER_FUNC(btlevtcmd_ftomsec, 9, LW(0))
                WAIT_MSEC(LW(0))
                USER_FUNC(_hammer_star_effect, -2, LW(13))
                CASE_END()
        END_SWITCH()
        SWITCH(LW(12))
            CASE_OR(PTR(&badgeWeapon_ConfuseHammer))
            CASE_OR(PTR(&badgeWeapon_TsuranukiNaguri))
                USER_FUNC(btlevtcmd_GetPos, -2, LW(0), LW(1), LW(2))
                USER_FUNC(btlevtcmd_snd_se, -2, PTR("SFX_BTL_MARIO_HAMMER_SHINE1"), PTR(0xf1194d80), 0, PTR(0xf1194d80))
                CASE_END()
        END_SWITCH()
    END_BROTHER()
    USER_FUNC(btlevtcmd_ftomsec, 30, LW(0))
    WAIT_MSEC(LW(0))
    USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, LW(1))
    USER_FUNC(btlevtcmd_StartAC, 0)
    USER_FUNC(btlevtcmd_ResultAC)
    USER_FUNC(_get_mario_hammer_lv, LW(0))
    SWITCH(LW(0))
        CASE_EQUAL(2)
            USER_FUNC(evt_snd_sfxon, PTR("SFX_MARIO_HAMMER_SWING2"), 0)
        CASE_EQUAL(1)
            USER_FUNC(evt_snd_sfxon, PTR("SFX_MARIO_HAMMER_SWING1"), 0)
        CASE_ETC()
            USER_FUNC(evt_snd_sfxon, PTR("SFX_MARIO_HAMMER_SWING3"), 0)
    END_SWITCH()
    USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, LW(2))
    WAIT_FRM(7)
    IF_EQUAL(LW(12), PTR(&badgeWeapon_TsuranukiNaguri))
        USER_FUNC(evt_snd_sfxon, PTR("SFX_MARIO_HAMMER_TURANUKI1"), 0)
    ELSE()
        USER_FUNC(_get_mario_hammer_lv, LW(0))
        SWITCH(LW(0))
            CASE_EQUAL(2)
                USER_FUNC(evt_snd_sfxon, PTR("SFX_MARIO_HAMMER_HIT_GROUND3"), 0)
            CASE_EQUAL(1)
                USER_FUNC(evt_snd_sfxon, PTR("SFX_MARIO_HAMMER_HIT_GROUND2"), 0)
            CASE_ETC()
                USER_FUNC(evt_snd_sfxon, PTR("SFX_MARIO_HAMMER_HIT_GROUND1"), 0)
        END_SWITCH()
    END_IF()
    IF_NOT_EQUAL(LW(6), 1)
        IF_EQUAL(LW(6), 3)
            USER_FUNC(btlevtcmd_StartAvoid, LW(3), 38)
        END_IF()
        IF_EQUAL(LW(6), 6)
            USER_FUNC(btlevtcmd_StartAvoid, LW(3), 39)
        END_IF()
        IF_EQUAL(LW(6), 2)
            USER_FUNC(btlevtcmd_StartAvoid, LW(3), 40)
        END_IF()
        GOTO(90)
    END_IF()
    USER_FUNC(btlevtcmd_GetResultAC, LW(6))
    IF_NOT_FLAG(LW(6), 0x2)
        USER_FUNC(btlevtcmd_CheckDamage, -2, LW(3), LW(4), LW(12), 256, LW(5))
        USER_FUNC(btlevtcmd_AudienceDeclareACResult, LW(12), -1)
        GOTO(90)
    END_IF()
    USER_FUNC(btlevtcmd_CheckDamage, -2, LW(3), LW(4), LW(12), 131328, LW(5))
    USER_FUNC(evt_btl_camera_set_moveSpeedLv, 0, 0)
    USER_FUNC(evt_btl_camera_set_zoom, 0, 250)
    USER_FUNC(btlevtcmd_GetResultPrizeLv, LW(3), 0, LW(6))
    USER_FUNC(btlevtcmd_GetHitPos, LW(3), LW(4), LW(0), LW(1), LW(2))
    USER_FUNC(btlevtcmd_ACSuccessEffect, LW(6), LW(0), LW(1), LW(2))
    USER_FUNC(btlevtcmd_AudienceDeclareACResult, LW(12), LW(6))
    LBL(90)
    USER_FUNC(btlevtcmd_StopAC)
    USER_FUNC(btlevtcmd_GetDamage, LW(3), LW(0))
    IF_LARGE_EQUAL(LW(0), 10)
        SET(LW(0), 9)
    END_IF()
    USER_FUNC(evt_btl_camera_shake_h, 0, LW(0), 0, 10, 13)
    USER_FUNC(btlevtcmd_WeaponAftereffect, LW(12))
    USER_FUNC(btlevtcmd_ACRStart, -2, 0, 12, 60, 0)
    USER_FUNC(btlevtcmd_ACRGetResult, LW(15), LW(13))
    IF_EQUAL(LW(15), 1)
        GOTO(91)
    END_IF()
    IF_SMALL_EQUAL(LW(15), -1)
        GOTO(91)
    END_IF()
    GOTO(92)
    LBL(91)
    USER_FUNC(evt_audience_acrobat_notry)
    SET(LW(0), 60)
    SUB(LW(0), LW(13))
    IF_LARGE_EQUAL(LW(0), 1)
        WAIT_FRM(LW(0))
    END_IF()
    IF_EQUAL(LW(12), PTR(&badgeWeapon_TsuranukiNaguri))
        USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, PTR("M_H_16"))
    ELSE()
        USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, PTR("M_S_1"))
    END_IF()
    WAIT_FRM(10)
    GOTO(95)
    LBL(92)
    IF_NOT_EQUAL(LW(15), 0)
        USER_FUNC(evt_btl_camera_set_mode, 0, 0)
        USER_FUNC(evt_btl_camera_set_moveSpeedLv, 0, 1)
        USER_FUNC(btlevtcmd_AudienceDeclareAcrobatResult, LW(12), 1, 0, 0, 0)
        BROTHER_EVT()
            USER_FUNC(btlevtcmd_snd_voice, -2, 1)
            USER_FUNC(btlevtcmd_SetRotateOffset, -2, 0, 20, 0)
            DO(30)
                USER_FUNC(btlevtcmd_AddRotate, -2, 0, 0, 12)
                WAIT_FRM(1)
            WHILE()
        END_BROTHER()
        BROTHER_EVT()
            WAIT_FRM(8)
            USER_FUNC(btlevtcmd_ACRStart, -2, 12, 25, 25, 0)
        END_BROTHER()
        BROTHER_EVT()
            WAIT_FRM(4)
            USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, PTR("M_Z_1"))
        END_BROTHER()
        USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, PTR("M_A_3A"))
        USER_FUNC(btlevtcmd_SetFallAccel, -2, FLOAT(0.2998046875))
        USER_FUNC(btlevtcmd_GetPos, -2, LW(0), LW(1), LW(2))
        USER_FUNC(btlevtcmd_FaceDirectionSub, -2, LW(0), 35)
        USER_FUNC(btlevtcmd_JumpPosition, -2, LW(0), LW(1), LW(2), 30, -1)
        WAIT_FRM(4)
        USER_FUNC(btlevtcmd_ACRGetResult, LW(0), LW(1))
        IF_EQUAL(LW(14), 0)
            IF_EQUAL(LW(0), 2)
                USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, PTR("M_A_3B"))
                USER_FUNC(btlevtcmd_GetPos, -2, LW(0), LW(1), LW(2))
                ADD(LW(1), 50)
                USER_FUNC(evt_eff::evt_eff, PTR("_BTLEF"), PTR("confetti"), 3, LW(0), LW(1), LW(2), 90, 0, 0, 0, 0, 0, 0, 0)
                USER_FUNC(btlevtcmd_AudienceDeclareAcrobatResult, LW(12), 1, 0, 0, 0)
                WAIT_FRM(90)
                GOTO(95)
            ELSE()
                USER_FUNC(evt_audience_acrobat_notry)
                GOTO(95)
            END_IF()
        ELSE()
            SWITCH(LW(0))
                CASE_EQUAL(2)
                    USER_FUNC(btlevtcmd_AudienceDeclareAcrobatResult, LW(12), 1, 0, 0, 0)
                CASE_EQUAL(1)
                    USER_FUNC(evt_audience_acrobat_notry)
                    GOTO(95)
            END_SWITCH()
        END_IF()
        BROTHER_EVT()
            USER_FUNC(btlevtcmd_snd_voice, -2, 1)
            USER_FUNC(btlevtcmd_SetRotateOffset, -2, 0, 20, 0)
            DO(40)
                USER_FUNC(btlevtcmd_AddRotate, -2, 0, 0, 18)
                WAIT_FRM(1)
            WHILE()
        END_BROTHER()
        BROTHER_EVT()
            WAIT_FRM(18)
            USER_FUNC(btlevtcmd_ACRStart, -2, 12, 25, 25, 0)
        END_BROTHER()
        BROTHER_EVT()
            WAIT_FRM(18)
            USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, PTR("M_Z_1"))
        END_BROTHER()
        USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, PTR("M_A_3A"))
        USER_FUNC(btlevtcmd_SetFallAccel, -2, FLOAT(0.2998046875))
        USER_FUNC(btlevtcmd_GetPos, -2, LW(0), LW(1), LW(2))
        USER_FUNC(btlevtcmd_FaceDirectionSub, -2, LW(0), 40)
        USER_FUNC(btlevtcmd_JumpPosition, -2, LW(0), LW(1), LW(2), 40, -1)
        WAIT_FRM(4)
        USER_FUNC(btlevtcmd_ACRGetResult, LW(0), LW(1))
        IF_NOT_EQUAL(LW(0), 2)
            GOTO(95)
        END_IF()
        USER_FUNC(btlevtcmd_AudienceDeclareAcrobatResult, LW(12), 1, 0, 0, 0)
        USER_FUNC(btlevtcmd_snd_voice, -2, 1)
        USER_FUNC(btlevtcmd_SetRotateOffset, -2, 0, 20, 0)
        BROTHER_EVT()
            DO(60)
                USER_FUNC(btlevtcmd_AddRotate, -2, 0, 12, 12)
                WAIT_FRM(1)
            WHILE()
            USER_FUNC(btlevtcmd_SetRotate, -2, 0, 0, 0)
        END_BROTHER()
        BROTHER_EVT()
            WAIT_FRM(35)
            USER_FUNC(btlevtcmd_ACRStart, -2, 15, 28, 28, 0)
        END_BROTHER()
        USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, PTR("M_C_3"))
        USER_FUNC(btlevtcmd_SetFallAccel, -2, FLOAT(0.19921875))
        USER_FUNC(btlevtcmd_GetPos, -2, LW(0), LW(1), LW(2))
        USER_FUNC(btlevtcmd_FaceDirectionSub, -2, LW(0), 50)
        USER_FUNC(btlevtcmd_JumpPosition, -2, LW(0), LW(1), LW(2), 60, -1)
        WAIT_FRM(4)
        USER_FUNC(btlevtcmd_ACRGetResult, LW(0), LW(1))
        IF_NOT_EQUAL(LW(0), 2)
            GOTO(95)
        END_IF()
        USER_FUNC(btlevtcmd_AudienceDeclareAcrobatResult, LW(12), 1, 0, 0, 0)
        USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, PTR("M_A_3B"))
        USER_FUNC(btlevtcmd_GetPos, -2, LW(0), LW(1), LW(2))
        ADD(LW(1), 50)
        USER_FUNC(evt_eff::evt_eff, PTR("_BTLEF"), PTR("confetti"), 3, LW(0), LW(1), LW(2), 90, 0, 0, 0, 0, 0, 0, 0)
        USER_FUNC(btlevtcmd_snd_voice, -2, 1)
        USER_FUNC(evt_snd_sfxon, PTR("SFX_BTL_ACROBAT_FINISH1"), 0)
        WAIT_FRM(90)
    END_IF()
    LBL(95)
    USER_FUNC(evt_audience_ap_recovery)
    USER_FUNC(btlevtcmd_InviteApInfoReport)
    USER_FUNC(evt_btl_camera_set_mode, 0, 0)
    USER_FUNC(evt_btl_camera_set_moveSpeedLv, 0, 1)
    USER_FUNC(btlevtcmd_SetRotate, -2, 0, 0, 0)
    USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, PTR("M_W_1"))
    USER_FUNC(btlevtcmd_SetMoveSpeed, -2, FLOAT(6.0))
    USER_FUNC(btlevtcmd_AnimeChangePoseType, -2, 1, 40)
    USER_FUNC(btlevtcmd_GetHomePos, -2, LW(0), LW(1), LW(2))
    USER_FUNC(btlevtcmd_MovePosition, -2, LW(0), LW(1), LW(2), 0, -1, 0)
    LBL(99)
    USER_FUNC(btlevtcmd_ResetFaceDirection, -2)
    RUN_CHILD_EVT(PTR(&btldefaultevt_SuitoruBadgeEffect))
    USER_FUNC(btlevtcmd_StartWaitEvent, -2)
    RETURN()
EVT_END()

EVT_BEGIN(override_hammer_evt)
  USER_FUNC(btlevtcmd_CommandGetWeaponAddress, -2, LW(12))
  USER_FUNC(btlevtcmd_check_battleflag, LW(0), 2)
  IF_EQUAL(LW(0), 0)
    USER_FUNC(btlevtcmd_GetWeaponActionLv, LW(12), LW(0))
    USER_FUNC(btlevtcmd_AcSetDifficulty, -2, LW(0))
    SWITCH(LW(12))
      CASE_EQUAL(PTR(&badgeWeapon_ConfuseHammer))
        RUN_CHILD_EVT(power_bounce)
      CASE_ETC()
        RUN_CHILD_EVT(hammer_move)
    END_SWITCH()
  END_IF()
RETURN()
EVT_END()

EVT_BEGIN(power_bounce)
    USER_FUNC(btlevtcmd_JumpSetting, -2, 20, FLOAT(0.0), FLOAT(0.69921875))
    USER_FUNC(btlevtcmd_GetSelectEnemy, LW(3), LW(4))
    IF_EQUAL(LW(3), -1)
        GOTO(99)
    END_IF()
    USER_FUNC(btlevtcmd_AttackDeclare, -2, LW(3), LW(4))
    USER_FUNC(btlevtcmd_WaitGuardMove)
    USER_FUNC(btlevtcmd_CommandPayWeaponCost, -2)
    USER_FUNC(btlevtcmd_RunDataEventChild, -2, 7)
    RUN_CHILD_EVT(PTR(&marioAttackEvent_MajinaiPowerUpCheck))
    USER_FUNC(evt_btl_camera_set_mode, 0, 11)
    USER_FUNC(evt_btl_camera_set_homing_unitparts, 0, -2, 1, LW(3), LW(4))
    USER_FUNC(evt_btl_camera_set_moveSpeedLv, 0, 1)
    USER_FUNC(evt_btl_camera_set_zoom, 0, 250)
    USER_FUNC(btlevtcmd_CommandGetWeaponActionLv, LW(0))
    USER_FUNC(btlevtcmd_AcSetDifficulty, -2, LW(0))
    USER_FUNC(btlevtcmd_SetupAC, -2, 1, 1, 0)
    USER_FUNC(btlevtcmd_ac_timing_flag_onoff, 1, 2)
    USER_FUNC(btlevtcmd_AnimeChangePoseType, -2, 1, 42)
    USER_FUNC(btlevtcmd_SetMoveSpeed, -2, FLOAT(3.0))
    USER_FUNC(btlevtcmd_GetTakeoffPosition, -2, LW(3), LW(4), LW(0), LW(1), LW(2))
    USER_FUNC(btlevtcmd_CalculateFaceDirection, -2, -1, LW(0), LW(2), 1, LW(15))
    USER_FUNC(btlevtcmd_ChangeFaceDirection, -2, LW(15))
    USER_FUNC(btlevtcmd_MovePosition, -2, LW(0), LW(1), LW(2), 0, -1, 0)
    USER_FUNC(btlevtcmd_CalculateFaceDirection, -2, -1, LW(3), LW(4), 16, LW(15))
    USER_FUNC(btlevtcmd_ChangeFaceDirection, -2, LW(15))
    USER_FUNC(btlevtcmd_StartAC, 1)
    USER_FUNC(_get_mario_hammer_lv, LW(0))
    SWITCH(LW(0))
        CASE_EQUAL(2)
            SET(LW(0), PTR("M_H_5A"))
            SET(LW(15), PTR("M_H_5B"))
            SET(LW(2), PTR("M_H_14"))
        CASE_EQUAL(3)
            SET(LW(0), PTR("M_H_9A"))
            SET(LW(15), PTR("M_H_9B"))
            SET(LW(2), PTR("M_H_15"))
        CASE_ETC()
            SET(LW(0), PTR("M_H_1A"))
            SET(LW(15), PTR("M_H_1B"))
            SET(LW(2), PTR("M_H_13"))
    END_SWITCH()
    USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, LW(0))
    WAIT_FRM(30)
    SET(LW(10), 0)
    LBL(10)
    USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, LW(15))
    IF_LARGE_EQUAL(LW(10), 1)
        USER_FUNC(btlevtcmd_CommandPreCheckDamage, -2, LW(3), LW(4), 1048832, LW(5))
    ELSE()
        USER_FUNC(btlevtcmd_CommandPreCheckDamage, -2, LW(3), LW(4), 256, LW(5))
    END_IF()
    SWITCH(LW(5))
        CASE_OR(2)
        CASE_OR(3)
        CASE_OR(6)
        CASE_OR(4)
            CASE_END()
        CASE_EQUAL(1)
        CASE_ETC()
            WAIT_MSEC(1000)
    END_SWITCH()
    INLINE_EVT()
        USER_FUNC(btlevtcmd_GetFaceDirection, -2, LW(5))
        MUL(LW(5), 45)
        USER_FUNC(evt_sub_intpl_init, 11, 0, LW(5), 10)
        DO(10)
            USER_FUNC(evt_sub_intpl_get_value)
            USER_FUNC(btlevtcmd_SetRotate, -2, 0, 0, LW(0))
            WAIT_FRM(1)
        WHILE()
        WAIT_FRM(8)
        USER_FUNC(btlevtcmd_SetRotateOffset, -2, 0, 20, 0)
        DO(30)
            USER_FUNC(btlevtcmd_AddRotate, -2, 0, 0, -12)
            WAIT_FRM(1)
        WHILE()
    END_INLINE()
    USER_FUNC(btlevtcmd_GetHitPos, LW(3), LW(4), LW(0), LW(1), LW(2))
    ADD(LW(2), 5)
    IF_LARGE_EQUAL(LW(10), 1)
        SET(LW(8), 36)
        USER_FUNC(btlevtcmd_MarioJumpParam, -2, LW(0), LW(1), LW(2), LW(8))
        SWITCH(LW(10))
            CASE_EQUAL(1)
                SET(LW(6), PTR("SFX_BTL_JUMP_CONTINUE2"))
            CASE_EQUAL(2)
                SET(LW(6), PTR("SFX_BTL_JUMP_CONTINUE3"))
            CASE_EQUAL(3)
                SET(LW(6), PTR("SFX_BTL_JUMP_CONTINUE4"))
            CASE_EQUAL(4)
                SET(LW(6), PTR("SFX_BTL_JUMP_CONTINUE5"))
            CASE_EQUAL(5)
                SET(LW(6), PTR("SFX_BTL_JUMP_CONTINUE6"))
            CASE_EQUAL(6)
                SET(LW(6), PTR("SFX_BTL_JUMP_CONTINUE7"))
            CASE_EQUAL(7)
                SET(LW(6), PTR("SFX_BTL_JUMP_CONTINUE8"))
            CASE_EQUAL(8)
                SET(LW(6), PTR("SFX_BTL_JUMP_CONTINUE9"))
            CASE_ETC()
                SET(LW(6), PTR("SFX_BTL_JUMP_CONTINUE10"))
        END_SWITCH()
        USER_FUNC(btlevtcmd_SetMoveSoundDataWork, -2, LW(6), 0, 0, -1, -1, 0, 0)
        BROTHER_EVT()
            WAIT_FRM(3)
            USER_FUNC(btlevtcmd_ACRStart, -2, 10, 17, 30, 0)
            USER_FUNC(btlevtcmd_ACRGetResult, LW(6), LW(7))
            SWITCH(LW(6))
                CASE_LARGE_EQUAL(2)
                    USER_FUNC(evt_sub_random, 2, LW(0))
                    SWITCH(LW(0))
                        CASE_EQUAL(0)
                            //USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, PTR("M_A_4"))
                        CASE_EQUAL(1)
                            //USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, PTR("M_A_5"))
                        CASE_ETC()
                            //USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, PTR("M_A_6"))
                    END_SWITCH()
                    USER_FUNC(btlevtcmd_CommandGetWeaponAddress, -2, LW(0))
                    USER_FUNC(btlevtcmd_AudienceDeclareAcrobatResult, LW(0), 1, -60, -30, 0)
                    USER_FUNC(btlevtcmd_snd_voice, -2, 1)
                CASE_ETC()
                    USER_FUNC(evt_audience_acrobat_notry)
            END_SWITCH()
        END_BROTHER()
        USER_FUNC(btlevtcmd_MarioJumpPosition, -2, LW(0), LW(1), LW(2), LW(8), 3, -2)
    ELSE()
        USER_FUNC(btlevtcmd_snd_se, -2, PTR("SFX_VOICE_MARIO_BATTLE_JUMP1"), PTR(0xf1194d80), 0, PTR(0xf1194d80))
        USER_FUNC(btlevtcmd_SetMoveSoundDataWork, -2, PTR("SFX_BTL_JUMP_CONTINUE1"), 0, 0, -1, -1, 0, 0)
        SET(LW(8), 36)
        USER_FUNC(btlevtcmd_MarioJumpParam, -2, LW(0), LW(1), LW(2), LW(8))
        USER_FUNC(btlevtcmd_MarioJumpPosition, -2, LW(0), LW(1), LW(2), LW(8), 0, -2)
    END_IF()
    IF_NOT_EQUAL(LW(5), 1)
        IF_EQUAL(LW(5), 3)
            USER_FUNC(btlevtcmd_StartAvoid, LW(3), 38)
        END_IF()
        IF_EQUAL(LW(5), 6)
            USER_FUNC(btlevtcmd_StartAvoid, LW(3), 39)
        END_IF()
        IF_EQUAL(LW(5), 2)
            USER_FUNC(btlevtcmd_StartAvoid, LW(3), 40)
        END_IF()
        USER_FUNC(btlevtcmd_StopAC)
        USER_FUNC(btlevtcmd_JumpContinue, -2)
        USER_FUNC(btlevtcmd_snd_se, -2, PTR("SFX_VOICE_MARIO_LAND_DAMAGE1"), PTR(0xf1194d80), 0, PTR(0xf1194d80))
        USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, PTR("M_D_2"))
        WAIT_FRM(40)
        GOTO(95)
    END_IF()
    USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, PTR("M_J_1D"))
    USER_FUNC(btlevtcmd_ac_timing_flag_onoff, 1, 1)
    USER_FUNC(btlevtcmd_ac_timing_get_success_frame, LW(0))
    DIV(LW(0), 2)
    WAIT_FRM(LW(0))
    USER_FUNC(btlevtcmd_ac_timing_flag_onoff, 0, 1)
    USER_FUNC(btlevtcmd_ResultAC)
    USER_FUNC(btlevtcmd_GetResultAC, LW(6))
    IF_NOT_FLAG(LW(6), 0x2)
        USER_FUNC(btlevtcmd_CommandCheckDamage, -2, LW(3), LW(4), 256, LW(5))
        USER_FUNC(btlevtcmd_CommandGetWeaponAddress, -2, LW(0))
        IF_EQUAL(LW(10), 0)
            USER_FUNC(btlevtcmd_AudienceDeclareACResult, LW(0), -1)
        ELSE()
            SET(LW(6), LW(10))
            SUB(LW(6), 1)
            USER_FUNC(btlevtcmd_GetResultPrizeLv, LW(3), LW(6), LW(6))
            USER_FUNC(btlevtcmd_AudienceDeclareACResult, LW(0), LW(6))
        END_IF()
        USER_FUNC(btlevtcmd_StopAC)
        USER_FUNC(evt_btl_camera_set_mode, 0, 0)
        USER_FUNC(btlevtcmd_CommandGetWeaponAddress, -2, LW(0))
        USER_FUNC(btlevtcmd_WeaponAftereffect, LW(0))
        USER_FUNC(evt_audience_ap_recovery)
        USER_FUNC(btlevtcmd_InviteApInfoReport)
        USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, PTR("M_J_1B"))
        USER_FUNC(btlevtcmd_SetFallAccel, -2, FLOAT(0.69921875))
        USER_FUNC(btlevtcmd_GetPos, -2, LW(0), LW(1), LW(2))
        USER_FUNC(btlevtcmd_GetHomePos, -2, PTR(0xf1194d80), LW(1), PTR(0xf1194d80))
        USER_FUNC(btlevtcmd_FaceDirectionSub, -2, LW(0), 27)
        USER_FUNC(btlevtcmd_JumpPosition, -2, LW(0), LW(1), LW(2), 20, -1)
        USER_FUNC(btlevtcmd_SetFallAccel, -2, FLOAT(0.599609375))
        USER_FUNC(btlevtcmd_FaceDirectionSub, -2, LW(0), 20)
        USER_FUNC(btlevtcmd_JumpPosition, -2, LW(0), LW(1), LW(2), 12, -1)
        USER_FUNC(btlevtcmd_FaceDirectionSub, -2, LW(0), 8)
        USER_FUNC(btlevtcmd_JumpPosition, -2, LW(0), LW(1), LW(2), 8, -1)
        GOTO(95)
    END_IF()
    INLINE_EVT()
        USER_FUNC(evt_btl_camera_set_moveSpeedLv, 0, 0)
        USER_FUNC(evt_btl_camera_set_zoom, 0, 200)
        WAIT_FRM(10)
        USER_FUNC(evt_btl_camera_set_moveSpeedLv, 0, 2)
        USER_FUNC(evt_btl_camera_set_zoom, 0, 250)
    END_INLINE()
    USER_FUNC(btlevtcmd_snd_voice, -2, 2)
    USER_FUNC(btlevtcmd_GetResultCountAC, LW(6))
    USER_FUNC(_record_renzoku_count, LW(6))
    USER_FUNC(btlevtcmd_GetResultCountAC, LW(6))
    USER_FUNC(mario_get_renzoku_count_max, LW(3), LW(6), LW(7))
    IF_SMALL(LW(6), LW(7))
        USER_FUNC(btlevtcmd_CommandCheckDamage, -2, LW(3), LW(4), 131072, LW(5))
    ELSE()
        USER_FUNC(btlevtcmd_CommandCheckDamage, -2, LW(3), LW(4), 131328, LW(5))
    END_IF()
    ADD(LW(10), 1)
    SET(LW(1), GSW(32))
    SET(LW(2), GSW(35))
    MUL(LW(2), 256)
    ADD(LW(1), LW(2))
    IF_LARGE(LW(10), LW(1))
        SET(LW(0), LW(10))
        IF_LARGE(LW(0), 9999)
            SET(LW(0), 9999)
        END_IF()
        SET(LW(1), LW(0))
        MOD(LW(1), 256)
        SET(LW(2), LW(0))
        DIV(LW(2), 256)
        SET(GSW(32), LW(1))
        SET(GSW(35), LW(2))
    END_IF()
    SET(LW(0), LW(10))
    SUB(LW(0), 1)
    USER_FUNC(btlevtcmd_GetResultPrizeLv, LW(3), LW(0), LW(6))
    USER_FUNC(btlevtcmd_GetHitPos, LW(3), LW(4), LW(0), LW(1), LW(2))
    USER_FUNC(btlevtcmd_ACSuccessEffect, LW(6), LW(0), LW(1), LW(2))
    USER_FUNC(btlevtcmd_CommandGetWeaponAddress, -2, LW(0))
    USER_FUNC(btlevtcmd_AudienceDeclareACResult, LW(0), LW(6))
    USER_FUNC(btlevtcmd_GetResultCountAC, LW(6))
    IF_SMALL(LW(6), LW(7))
        WAIT_FRM(2)
        USER_FUNC(btlevtcmd_StartAC, 0)
        GOTO(10)
    END_IF()
    LBL(90)
    USER_FUNC(btlevtcmd_StopAC)
    USER_FUNC(evt_btl_camera_set_mode, 0, 0)
    USER_FUNC(btlevtcmd_CommandGetWeaponAddress, -2, LW(0))
    USER_FUNC(btlevtcmd_WeaponAftereffect, LW(0))
    USER_FUNC(evt_audience_ap_recovery)
    USER_FUNC(btlevtcmd_InviteApInfoReport)
    USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, PTR("M_J_1B"))
    USER_FUNC(btlevtcmd_SetFallAccel, -2, FLOAT(0.69921875))
    USER_FUNC(btlevtcmd_GetPos, -2, LW(0), LW(1), LW(2))
    USER_FUNC(btlevtcmd_GetHomePos, -2, PTR(0xf1194d80), LW(1), PTR(0xf1194d80))
    USER_FUNC(btlevtcmd_FaceDirectionSub, -2, LW(0), 60)
    USER_FUNC(btlevtcmd_JumpPosition, -2, LW(0), LW(1), LW(2), 30, -1)
    USER_FUNC(btlevtcmd_SetFallAccel, -2, FLOAT(0.599609375))
    USER_FUNC(btlevtcmd_FaceDirectionSub, -2, LW(0), 20)
    USER_FUNC(btlevtcmd_JumpPosition, -2, LW(0), LW(1), LW(2), 12, -1)
    USER_FUNC(btlevtcmd_FaceDirectionSub, -2, LW(0), 8)
    USER_FUNC(btlevtcmd_JumpPosition, -2, LW(0), LW(1), LW(2), 8, -1)
    LBL(95)
    USER_FUNC(evt_btl_camera_set_mode, 0, 0)
    USER_FUNC(evt_btl_camera_set_moveSpeedLv, 0, 1)
    INLINE_EVT()
        USER_FUNC(btlevtcmd_GetFaceDirection, -2, LW(5))
        MUL(LW(5), 45)
        USER_FUNC(evt_sub_intpl_init, 11, LW(5), 0, 10)
        DO(10)
            USER_FUNC(evt_sub_intpl_get_value)
            USER_FUNC(btlevtcmd_SetRotate, -2, 0, 0, LW(0))
            WAIT_FRM(1)
        WHILE()
    END_INLINE()
    USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, PTR("M_W_1"))
    USER_FUNC(btlevtcmd_SetMoveSpeed, -2, FLOAT(6.0))
    USER_FUNC(btlevtcmd_AnimeChangePoseType, -2, 1, 40)
    USER_FUNC(btlevtcmd_GetHomePos, -2, LW(0), LW(1), LW(2))
    USER_FUNC(btlevtcmd_MovePosition, -2, LW(0), LW(1), LW(2), 0, -1, 0)
    LBL(99)
    USER_FUNC(btlevtcmd_ResetFaceDirection, -2)
    RUN_CHILD_EVT(PTR(&btldefaultevt_SuitoruBadgeEffect))
    USER_FUNC(btlevtcmd_StartWaitEvent, -2)
    RETURN()
EVT_END()

EVT_BEGIN(vivian_woosh)
    SET(LW(3), -3)
    USER_FUNC(btlevtcmd_GetBodyId, LW(3), LW(4))
    USER_FUNC(btlevtcmd_CommandPayWeaponCost, -2)
    USER_FUNC(btlevtcmd_CommandGetWeaponAddress, -2, LW(12))
    USER_FUNC(btlevtcmd_RunDataEventChild, -2, 7)
    USER_FUNC(evt_btl_camera_set_mode, 0, 7)
    USER_FUNC(evt_btl_camera_set_homing_unit, 0, -2, 1)
    USER_FUNC(evt_btl_camera_set_moveSpeedLv, 0, 2)
    USER_FUNC(evt_btl_camera_set_zoom, 0, 250)
    USER_FUNC(evt_btl_camera_set_posoffset, 0, 20, 0, 0)
    USER_FUNC(btlevtcmd_CalculateFaceDirection, -2, -1, LW(3), -1, 16, LW(0))
    USER_FUNC(btlevtcmd_ChangeFaceDirection, -2, LW(0))
    USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, PTR("PTR_A2_1"))
    USER_FUNC(btlevtcmd_GetPos, LW(3), LW(0), LW(1), LW(2))
    USER_FUNC(btlevtcmd_FaceDirectionSub, LW(3), LW(0), 15)
    ADD(LW(2), 5)
    USER_FUNC(btlevtcmd_SetMoveSpeed, -2, FLOAT(2.0))
    USER_FUNC(btlevtcmd_MovePosition, -2, LW(0), LW(1), LW(2), 0, -1, 0)
    USER_FUNC(btlevtcmd_CalculateFaceDirection, -2, -1, LW(3), -1, 16, LW(0))
    USER_FUNC(btlevtcmd_ChangeFaceDirection, -2, LW(0))
    USER_FUNC(btlevtcmd_CommandGetWeaponActionLv, LW(0))
    USER_FUNC(btlevtcmd_AcSetDifficulty, -2, LW(0))
    USER_FUNC(btlevtcmd_CommandGetWeaponActionLv, LW(0))
    USER_FUNC(btlevtcmd_AcSetDifficulty, -2, LW(0))
    USER_FUNC(btlevtcmd_AcGetDifficulty, LW(0))
    SUB(LW(0), 3)
    SWITCH(LW(0))
        CASE_SMALL_EQUAL(-3)
            SET(LW(0), 420)
        CASE_EQUAL(-2)
            SET(LW(0), 330)
        CASE_EQUAL(-1)
            SET(LW(0), 270)
        CASE_EQUAL(0)
            SET(LW(0), 240)
        CASE_EQUAL(1)
            SET(LW(0), 200)
        CASE_EQUAL(2)
            SET(LW(0), 160)
        CASE_ETC()
            SET(LW(0), 120)
    END_SWITCH()
    USER_FUNC(btlevtcmd_AcSetParamAll, LW(0), 1, 5, -2, 5, PTR(0xf1194d80), PTR(0xf1194d80), PTR(0xf1194d80))
    USER_FUNC(btlevtcmd_AcSetFlag, 0)
    USER_FUNC(btlevtcmd_SetupAC, -2, 10, 1, 0)
    WAIT_FRM(22)
    USER_FUNC(btlevtcmd_StartAC, 1)
    USER_FUNC(btlevtcmd_ResultAC)
    USER_FUNC(btlevtcmd_GetResultAC, LW(0))
    IF_NOT_FLAG(LW(0), 0x2)
        USER_FUNC(btlevtcmd_AudienceDeclareACResult, LW(12), -1)
        USER_FUNC(btlevtcmd_StopAC)
        USER_FUNC(btlevtcmd_GetHomePos, -2, LW(0), LW(1), LW(2))
        USER_FUNC(btlevtcmd_SetMoveSpeed, -2, FLOAT(2.0))
        USER_FUNC(btlevtcmd_MovePosition, -2, LW(0), LW(1), LW(2), 0, -1, 0)
        GOTO(90)
    END_IF()
    USER_FUNC(btlevtcmd_GetResultPrizeLv, -1, 0, LW(6))
    USER_FUNC(btlevtcmd_GetHitPos, LW(3), LW(4), LW(0), LW(1), LW(2))
    USER_FUNC(btlevtcmd_ACSuccessEffect, LW(6), LW(0), LW(1), LW(2))
    USER_FUNC(btlevtcmd_AudienceDeclareACResult, LW(12), LW(6))
    USER_FUNC(btlevtcmd_StopAC)
    USER_FUNC(evt_btl_camera_set_moveSpeedLv, 0, 2)
    USER_FUNC(evt_btl_camera_set_zoom, 0, 350)
    USER_FUNC(evt_btl_camera_set_posoffset, 0, 0, 0, 0)
    USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, PTR("PTR_A2_2"))
    USER_FUNC(btlevtcmd_AnimeWaitPlayComplete, -2, 1)
    USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, PTR("PTR_A2_3"))
    USER_FUNC(btlevtcmd_AnimeWaitPlayComplete, -2, 1)
    BROTHER_EVT()
        USER_FUNC(btlevtcmd_AnimeChangePose, LW(3), 1, PTR("M_B_3"))
        USER_FUNC(battle_evt_majo_disp_off, LW(3), 1, 1, 0)
        USER_FUNC(btlevtcmd_OnAttribute, LW(3), 16)
        USER_FUNC(btlevtcmd_OnPartsAttribute, LW(3), 1, 50331648)
        WAIT_FRM(1)
        USER_FUNC(btlevtcmd_GetHomePos, LW(3), LW(0), LW(1), LW(2))
        USER_FUNC(btlevtcmd_SetPos, LW(3), LW(0), LW(1), LW(2))
    END_BROTHER()
    USER_FUNC(battle_evt_majo_disp_off, -2, 1, 1, 1)
    USER_FUNC(btlevtcmd_GetPos, -2, LW(0), LW(1), LW(2))
    USER_FUNC(btlevtcmd_GetPos, LW(3), LW(5), LW(1), LW(2))
    ADD(LW(0), LW(5))
    DIV(LW(0), 2)
    USER_FUNC(btlevtcmd_TransStageFloorPosition, LW(0), LW(1), LW(2))
    ADD(LW(1), 1)
    USER_FUNC(evt_eff::evt_eff, 0, PTR("ripple"), 1, LW(0), LW(1), LW(2), 0, 0, 0, 0, 0, 0, 0, 0)
    WAIT_MSEC(333)
    USER_FUNC(btlevtcmd_OnPartsAttribute, -2, 1, 16842752)
    WAIT_FRM(1)
    USER_FUNC(btlevtcmd_SetUnitWork, -2, 4, 1)
    USER_FUNC(btlevtcmd_GetPos, -2, LW(0), LW(1), LW(2))
    USER_FUNC(btlevtcmd_TransStageFloorPosition, LW(0), LW(1), LW(2))
    USER_FUNC(btlevtcmd_SetPos, -2, LW(0), LW(1), LW(2))
    WAIT_FRM(1)
    USER_FUNC(btlevtcmd_CalculateFaceDirection, -2, -1, -1, -1, 4, LW(0))
    USER_FUNC(btlevtcmd_ChangeFaceDirection, -2, LW(0))
    WAIT_MSEC(500)
    LBL(90)
    USER_FUNC(evt_audience_ap_recovery)
    USER_FUNC(btlevtcmd_InviteApInfoReport)
    LBL(95)
    USER_FUNC(evt_btl_camera_set_mode, 0, 0)
    USER_FUNC(evt_btl_camera_set_moveSpeedLv, 0, 1)
    USER_FUNC(evt_btl_camera_set_posoffset, 0, 0, 0, 0)
    LBL(99)
    USER_FUNC(btlevtcmd_StartWaitEvent, -2)
    RETURN()
EVT_END()

EVT_BEGIN(return_from_shadows)
    USER_FUNC(btlevtcmd_GetUnitWork, -2, 4, LW(0))
    IF_LARGE_EQUAL(LW(0), 1)
        SUB(LW(0), 1)
    END_IF()
    USER_FUNC(btlevtcmd_SetUnitWork, -2, 4, LW(0))
    IF_SMALL_EQUAL(LW(0), 0)
        SET(LW(3), -3)
        USER_FUNC(btlevtcmd_PhaseEventStartDeclare, LW(3))
        USER_FUNC(btlevtcmd_GetPos, LW(3), LW(0), LW(1), LW(2))
        USER_FUNC(btlevtcmd_FaceDirectionSub, LW(3), LW(0), 15)
        USER_FUNC(btlevtcmd_SetPos, -2, LW(0), LW(1), LW(2))
        INLINE_EVT()
            USER_FUNC(btlevtcmd_OffAttribute, LW(3), 16)
            USER_FUNC(btlevtcmd_OffPartsAttribute, LW(3), 1, 50331648)
            USER_FUNC(battle_evt_majo_disp_on, LW(3), 1, LW(0), LW(1), LW(2), 1)
            USER_FUNC(btlevtcmd_SetPos, LW(3), LW(0), LW(1), LW(2))
            USER_FUNC(btlevtcmd_GetHomePos, LW(3), LW(0), LW(1), LW(2))
            USER_FUNC(btlevtcmd_SetMoveSpeed, LW(3), FLOAT(2.0))
            USER_FUNC(btlevtcmd_MovePosition, LW(3), LW(0), LW(1), LW(2), 0, -1, 0)
        END_INLINE()
        USER_FUNC(btlevtcmd_OffPartsAttribute, -2, 1, 65536)
        USER_FUNC(btlevtcmd_OffPartsAttribute, -2, 1, 16777216)
        USER_FUNC(battle_evt_majo_disp_on, -2, 1, LW(0), LW(1), LW(2), 1)
        USER_FUNC(btlevtcmd_SetPos, -2, LW(0), LW(1), LW(2))
        USER_FUNC(btlevtcmd_GetHomePos, -2, LW(0), LW(1), LW(2))
        USER_FUNC(btlevtcmd_GetMoveFrame, -2, LW(0), LW(1), LW(2), FLOAT(2.0), LW(15))
        BROTHER_EVT_ID(LW(14))
            USER_FUNC(btlevtcmd_MovePosition, -2, LW(0), LW(1), LW(2), LW(15), -1, 0)
        END_BROTHER()
        USER_FUNC(btlevtcmd_ACRStart, -2, 0, LW(15), LW(15), 15)
        USER_FUNC(btlevtcmd_ACRGetResult, LW(6), LW(7))
        SWITCH(LW(6))
            CASE_LARGE_EQUAL(2)
                DELETE_EVT(LW(14))
                USER_FUNC(btlevtcmd_AudienceDeclareAcrobatResult, PTR(&partyWeapon_VivianShadowGuard), 1, 0, 0, 0)
                USER_FUNC(btlevtcmd_AnimeChangePose, -2, 1, PTR("PTR_Y_1"))
                USER_FUNC(btlevtcmd_GetHomePos, -2, LW(0), LW(1), LW(2))
                USER_FUNC(btlevtcmd_SetMoveSpeed, -2, FLOAT(2.0))
                USER_FUNC(btlevtcmd_MovePosition, -2, LW(0), LW(1), LW(2), 0, -1, 0)
                USER_FUNC(btlevtcmd_AnimeWaitPlayComplete, -2, 1)
            CASE_ETC()
                USER_FUNC(evt_audience_acrobat_notry)
                USER_FUNC(btlevtcmd_WaitEventEnd, LW(14))
        END_SWITCH()
        USER_FUNC(evt_audience_ap_recovery)
        USER_FUNC(btlevtcmd_InviteApInfoReport)
        USER_FUNC(btlevtcmd_StartWaitEvent, LW(3))
        USER_FUNC(btlevtcmd_StartWaitEvent, -2)
    END_IF()
    USER_FUNC(btlevtcmd_SetUnitWork, -2, 4, 1)
    USER_FUNC(vivian_buff)
    RETURN()
EVT_END()


}